FROM mysql 

RUN apt-get update 
RUN apt-get install -y sqlite3 wget

WORKDIR /workspace
RUN wget https://gist.githubusercontent.com/esperlu/943776/raw/be469f0a0ab8962350f3c5ebe8459218b915f817/mysql2sqlite.sh

